language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
install:
  - composer install
notifications:
  slack:
    secure: uYRnCVQ5TI+DnywmuyMWRMzntnopb0U5R4zggVX36zu0rzFfGgZ22SJzaxYG9aS0s75ICsl/HF5K66cqAr9tpsR4Vzg2qXEINQce2/vcfGmRJaWyT/dHJRGUX0RwA8PYY889+y55yyP6mVRr+mQjbYYZha1TGkJMVHEvHnoJFriDJJmtFGSVfPGNiCNqqGztdJn0dX80xa+Cue1mka35uULg3k/rn5c5ojMDmKmFxijK5an2Ez/IQmHptLVpD21lfb3DV+e4iuCskODmc2gk7oDzsZRIRIbiDRpZTYJlFmq4Z9cr3iH2UH94U5e34pAsgn4nohEIW2J8ehbuPRujBwEZTFlZOsAywFhD7HMp/41OqEpF84aCQwJ1Hod8gEDb/oCE/87i+vYdOqDc7mqWG4ld7Gp2g3p7O3kHO7jSJ3M7gTDyMQPsTmkcKX3YzutiLssLL9LUCUaMp0Z4gCYkAAV+dQN+tCtkTvodpGD6if4nHPP7LeqCXbPWOu2S30kM+IseCTMcM6d3ilgyQj8RqKtjR1TXWw+7v7ASMuiokBomzinjSGgUY2uYfmR0jUp633sMim1UX/mVVU8e5z0BNw3LFH8SU8Ct/TIpTiTGAXVgZhDGgdtQMbWaRgwllBuLVq+mw8Z4IJ/++/OK+/QbNcvg9qqLLnZReFGhfmkAlBY=
