language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
install:
  - composer install
notifications:
  slack:
    secure: C9+i3BhNobNTB+LIiFwVSHeBDX8vXmJhMisqcwAOmfbeNi/cY6Hbws384BBvvI01DSAIIAk8YQsHB3DPqW2tEenRFWayVTOSM6AHG4tk/cO6wf80pD+Ql/sWghMxtbUzWGDa/pcTM/FbpmqK1wh4Mtm9ShU5PSUKE8LqSIg0tHdZxQJp23OtuD0iiHNxyI+cEDR6CIubTTZtuRvrzhc/2BbtYNp/Tu8Ypy2nzUXcwVrZbOqakPtcnqU73dDR9UuRhr5o+xgA9EAtQtrGp2LqbzuCpY1RsCMMYuoVW/+YhcSzFTz4hJ8Gyw8BA/A6SIPUChR3m1eAkjzRT8S7nX70cNLnps1f/D0X4ihMnwxi5Q2DO5PNF1rylcgSMR/CKm7rHQW6u/iiXIaIRoA0hZOdXSAFhy5LLMOO8enZBsh3MAIZfxpjAIg7+IGzzOANIbO9pOe3CvP3AyVoNCN97hh1k6I56E+pZ5R6GrWIY7+Os1ZKXr7QPXvJm8yXXwWtuWR+Sor+qlO5GUlf3T2xaf97beeq2Lp5UV3HPqOR4OLhrMdU6VPsRIj/OjQh8xZgPpbspYpJE3MnkRuPWNc5/DRjprWzxnVxKmHJClRH0K1KXFOtonLTC73gArViHr5/KSmrvYtbf7EFuiE3zKny0ih4UgXdcoK4dSILPpjRkFSZqM8=
